In [1]:
import pandas as pd

df = pd.read_csv('tiktok_shop_products_updated.csv')

df.head()

,product_id,title,link,category,label_trend,label_marketing,rating,sold,original_price,current_price,discount_percent,update_at
0,1731982884920395437,(MỞ BÁN) Áo cardigan Dáng Ngắn BYJANE-999,https://www.tiktok.com/shop/vn/pdp/ao-cardigan...,Womenswear & Underwear,"{'product_id': 1731982884920395437, 'label_tre...",Deal,4.8,802K,110.000₫,49.499₫,-55%,2026-01-22 08:37:07.048964
1,1732477576245380758,Có BIGSIZE. Áo bí 2 dây babydoll basic dáng rộ...,https://www.tiktok.com/shop/vn/pdp/ao-babydoll...,Womenswear & Underwear,"{'product_id': 1732477576245380758, 'label_tre...",Deal,4.8,10K,185.000₫,94.000₫,-49%,2026-01-22 08:37:07.048964
2,1732242929860511562,"Áo Khoác Cardigan JUSTDUN 201 Nữ - Dáng Vừa, V...",https://www.tiktok.com/shop/vn/pdp/ao-khoac-ca...,Womenswear & Underwear,"{'product_id': 1732242929860511562, 'label_tre...",Không,4.7,527K,70.000₫,54.000₫,-23%,2026-01-22 08:37:07.048964
3,1733056843041572154,"Đồ bộ tole nữ tay dài quần dài , đồ bộ nữ mặc ...",https://www.tiktok.com/shop/vn/pdp/%C4%91o-bo-...,Womenswear & Underwear,"{'product_id': 1733056843041572154, 'label_tre...",Không,4.7,14K,228.000₫,124.600₫,-45%,2026-01-22 08:37:07.048964
4,1732295703259743988,Áo Phao Cổ Lông Trần Bông Dáng Vừa Cho Nữ Kiểu...,https://www.tiktok.com/shop/vn/pdp/ao-phao-co-...,Womenswear & Underwear,"{'product_id': 1732295703259743988, 'label_tre...",Không,4.7,136K,300.000₫,157.000₫,-48%,2026-01-22 08:37:07.048964

In [34]:
df_new = df.copy()
df_new['label_trend'] = df_new['label_trend'].str.extract(r"'label_trend': '([^']*)'")
df_new.head()

,product_id,title,link,category,label_trend,label_marketing,rating,sold,original_price,current_price,discount_percent,update_at
0,1731982884920395437,(MỞ BÁN) Áo cardigan Dáng Ngắn BYJANE-999,https://www.tiktok.com/shop/vn/pdp/ao-cardigan...,Womenswear & Underwear,Xu hướng,Deal,4.8,802K,110.000₫,49.499₫,-55%,2026-01-22 08:37:07.048964
1,1732477576245380758,Có BIGSIZE. Áo bí 2 dây babydoll basic dáng rộ...,https://www.tiktok.com/shop/vn/pdp/ao-babydoll...,Womenswear & Underwear,Không,Deal,4.8,10K,185.000₫,94.000₫,-49%,2026-01-22 08:37:07.048964
2,1732242929860511562,"Áo Khoác Cardigan JUSTDUN 201 Nữ - Dáng Vừa, V...",https://www.tiktok.com/shop/vn/pdp/ao-khoac-ca...,Womenswear & Underwear,Xu hướng,Không,4.7,527K,70.000₫,54.000₫,-23%,2026-01-22 08:37:07.048964
3,1733056843041572154,"Đồ bộ tole nữ tay dài quần dài , đồ bộ nữ mặc ...",https://www.tiktok.com/shop/vn/pdp/%C4%91o-bo-...,Womenswear & Underwear,Không,Không,4.7,14K,228.000₫,124.600₫,-45%,2026-01-22 08:37:07.048964
4,1732295703259743988,Áo Phao Cổ Lông Trần Bông Dáng Vừa Cho Nữ Kiểu...,https://www.tiktok.com/shop/vn/pdp/ao-phao-co-...,Womenswear & Underwear,Xu hướng,Không,4.7,136K,300.000₫,157.000₫,-48%,2026-01-22 08:37:07.048964

In [35]:
df_new.to_csv('tiktok_shop_products_cleaned.csv', index=False)